---
title: "Fancy Flex Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
```

# Page 1



Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r plot1}

ggplot(mpg, aes(displ, cty)) +
  geom_point(color = "orange") +
  geom_smooth() +
  facet_wrap(~class, ncol = 3) +
  labs(title = "Classic Plot w. Class")



```



Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

ggplot(mpg, aes(displ, cty)) +
  geom_point(color = "cornflowerblue") +
  geom_smooth() +
  facet_wrap(~class) +
  labs(title = "Classic Plot w. Class")


```

### Chart C

```{r plot3, fig.height = 8}

ggplot(mpg, aes(displ, cty)) +
  geom_point(color = "magenta") +
  geom_smooth() +
  labs(title = "Classic Plot")

```


# Page 2

Column {data-width=350}
-----------------------------------------------------------------------

### Chart A

```{r plot11}

ggplot(mpg, aes(displ, cty)) +
  geom_point(color = "orange") +
  geom_smooth() +
  facet_wrap(~class, ncol = 3) +
  labs(title = "Classic Plot w. Class But Different")



```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart B

```{r}

p <- ggplot(mpg, aes(displ, cty)) +
  geom_point(color = "cornflowerblue") +
  geom_smooth() +
  facet_wrap(~class) +
  labs(title = "Classic Plot w. Class")

ggplotly(p)


```

### Chart C

```{r plot31, fig.height = 2}

ggplot(mpg, aes(displ, cty)) +
  geom_point(color = "magenta") +
  geom_smooth() +
  labs(title = "Classic Plot")

```